### ISSUE TITLE
incorrect spelling

### ISSUE THREAD

**Issue by matthewhutchings** [cwd/datamolino-client#1]
datamolino-client/Endpoints/DocumentEndpoint.php line 131 incorrect spelling of documents

**Comment by rufinus** [comment]
thanks.

Fixt by https://github.com/cwd/datamolino-client/releases/tag/1.2.2.2

**Comment by matthewhutchings** [comment]
Silly Question, but how would I access the returned document id from the
create method..

// Upload multiple documents via finder$finder = new
Finder();$documents =
$datamolino->document()->createByFinder($finder->in('../testdata'),
4050, Document::DOCTYPE_PURCHASE, false, true);



Response:

Cwd\Datamolino\Model\Document Object
(
    [id:Cwd\Datamolino\Model\Document:private] => 270585
    [type:Cwd\Datamolino\Model\Document:private] =>
    [created_at:Cwd\Datamolino\Model\Document:private] =>
    [last_modified_at:Cwd\Datamolino\Model\Document:private] =>
    [state:Cwd\Datamolino\Model\Document:private] =>
    [verificator_response:Cwd\Datamolino\Model\Document:private] =>
    [preview:Cwd\Datamolino\Model\Document:private] =>
    [original:Cwd\Datamolino\Model\Document:private] =>
    [user_file_name:Cwd\Datamolino\Model\Document:private] =>
    [invoice_type:Cwd\Datamolino\Model\Document:private] =>
    [parent_document_id:Cwd\Datamolino\Model\Document:private] =>
    [data:Cwd\Datamolino\Model\Document:private] =>
    [bank_account:Cwd\Datamolino\Model\Document:private] =>
    [supplier:Cwd\Datamolino\Model\Document:private] =>
    [customer:Cwd\Datamolino\Model\Document:private] =>
    [summary:Cwd\Datamolino\Model\Document:private] =>
    [tax_lines:Cwd\Datamolino\Model\Document:private] => Array
        (
        )

    [items:Cwd\Datamolino\Model\Document:private] => Array
        (
        )

)


As the ID is private, I am unable to access this?



On 31 October 2018 at 19:11:26, Ludwig Ruderstaller (
notifications@github.com) wrote:

Closed #1 <https://github.com/cwd/datamolino-client/issues/1>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cwd/datamolino-client/issues/1#event-1938793827>, or mute
the thread

**Comment by rufinus** [comment]
The document object has get deter for all fields.

    $document->getId()
