### ISSUE TITLE
Unable to specify host URL

### ISSUE THREAD

**Issue by matthewhutchings** [cwd/datamolino-client#2]
Using Laravel and datamolino-client, I seem to be unable to set the host to app.datamolino and it defaults to beta. 

I have set it up this way

>   $token = $datamolino->getClient()->authenticatePassword(
>             env('DATAMOLINO_CLIENT_ID'),
>             env('DATAMOLINO_CLIENT_SECRET'),
>             env('DATAMOLINO_USERNAME'),
>             env('DATAMOLINO_PASSWORD')
>         );
> 

However this does not allow me to set the host and I can't figure out the way to do it.

**Comment by rufinus** [comment]
You are right, this is not ideal, i will change this in an upcoming version.
(i mostly use the symfony integration)

Try this in the meantime:
```
$url = 'https://app.datamolino.com';
$token = $datamolino->getClient()
    ->setApiUrl('https://app.datamolino.com')
    ->setTokenUrl($url.'/oauth/token')
    ->setApiUri(sprintf('%s/api/%s/', $url, $datamolino->getClient()->getApiVersion())
    ->authenticatePassword(
        env('DATAMOLINO_CLIENT_ID'),
        env('DATAMOLINO_CLIENT_SECRET'),
        env('DATAMOLINO_USERNAME'),
        env('DATAMOLINO_PASSWORD')
    )
;
```

**Comment by rufinus** [comment]
Should be fixt in https://github.com/cwd/datamolino-client/tree/1.2.3.4

```
$token = $datamolino->getClient()
    ->setApiUrl('https://app.datamolino.com')
    ->authenticatePassword(
        env('DATAMOLINO_CLIENT_ID'),
        env('DATAMOLINO_CLIENT_SECRET'),
        env('DATAMOLINO_USERNAME'),
        env('DATAMOLINO_PASSWORD')
    )
;
```
