### ISSUE TITLE
Unable to proces split document 

### ISSUE THREAD

**Issue by matthewhutchings** [cwd/datamolino-client#3]
Hi,

If you submit a document which has multiple invoices in, the document will be split by Dataolino, and they provide you back Json with multiple documents in. Using this package, it is unable to process any of the other documents.

Example: A PDF document which has 5 pages, each page is a different invoice. The first ID received back after submitting the document is 272491, the split documents are broken into 272492, 272493, 272494, 272495 and provided back within the documents object. However using 

`$document = $datamolino->document()->get(272491);
`
Only returns the first document of 272492

**Comment by rufinus** [comment]
Thanks for reporting.I will take a look in the next days. Document splitting wasn't one of my use cases.

**Comment by rufinus** [comment]
@matthewhutchings  see Release 1.2.3.5 - now when you fetch a specific document which was a splitFile it will return all generated documents.

I'm also in talk with datamolino - because when you fetch per list with the `?ids[]=272491` - `null` is returned instead of the collection

**Comment by rufinus** [comment]
i got feedback from datamolino:

> 1.) “list of documents” (e.g. ?ids[]=272534) now returns parent document 
> detail, with field state set to ‘parent’
> 2.) when this happens you can request children by calling 
> api/v1_2/documents/272534
